//! The app itself: a six-state machine with a boarding pass.

use std::collections::BTreeMap;

use leptos::prelude::*;

use crate::components::{Confetti, DayStrip, ThemeToggle};
use crate::data::{Choice, BUSY_DAYS, HER_BIRTHDAY, JOINS, LEGS, VIBES};
use crate::util::{compress_days, Avail, Rng};

/// The flow, made illegal-state-proof by the type system.
/// You cannot pick vibes before seeing the route. The compiler is the chaperone.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum Step {
    Intro,
    Route,
    Days,
    Join,
    Vibes,
    Done,
}

#[component]
pub fn App() -> impl IntoView {
    let step = RwSignal::new(Step::Intro);

    // Selections. Days map to how free she is; absence means unmarked.
    let avail: RwSignal<BTreeMap<u32, Avail>> = RwSignal::new(BTreeMap::new());
    let joins: RwSignal<Vec<&'static str>> = RwSignal::new(Vec::new());
    let vibes: RwSignal<Vec<&'static str>> = RwSignal::new(Vec::new());

    // The text that was on the clipboard as of the last copy — `None` before
    // the first copy, `Some(stale text)` if she's since changed a selection.
    let copied_snapshot: RwSignal<Option<String>> = RwSignal::new(None);

    // The shy escape hatch. "none of these days work" dodges the first three
    // approaches — hover or click — then holds still and leads to the graceful
    // not-free ending. Leaving the screen un-tames it: every visit starts shy.
    let not_free = RwSignal::new(false);
    let shy_pos = RwSignal::new((0.0f64, 0.0f64));
    let dodges = RwSignal::new(0u32);
    // Debounce: pointermove fires in bursts, and a move-dodge followed by a
    // click lands within milliseconds — one approach should cost one dodge.
    let last_dodge = RwSignal::new(0.0f64);
    let dodge = move || {
        let now = js_sys::Date::now();
        if now - last_dodge.get_untracked() < 250.0 {
            return;
        }
        last_dodge.set(now);
        let n = dodges.get_untracked() + 1;
        dodges.set(n);
        if n >= 3 {
            // The surrender: walk back to center and hold still there.
            shy_pos.set((0.0, 0.0));
        } else {
            let mut rng = Rng::from_clock();
            // Always hop to the other side of the row, so it can't land back
            // under the cursor and eat a second dodge for free.
            let (prev_x, _) = shy_pos.get_untracked();
            let x = if prev_x >= 0.0 {
                rng.range(-70.0, -25.0)
            } else {
                rng.range(25.0, 70.0)
            };
            shy_pos.set((x, rng.range(-26.0, 26.0)));
        }
    };
    let shy_click = move |_: web_sys::MouseEvent| {
        if dodges.get_untracked() < 3 {
            dodge();
        } else {
            not_free.set(true);
            step.set(Step::Done);
        }
    };
    // pointermove, not pointerenter: a screen change can re-render the button
    // underneath a parked cursor (the previous screen's next button sits
    // nearby), and enter fires without the mouse moving — only a mouse that's
    // actually approaching should scare it. Mouse pointers only, so taps keep
    // the full three-tap chase on phones.
    let shy_hover = move |ev: web_sys::PointerEvent| {
        if ev.pointer_type() == "mouse" && dodges.get_untracked() < 3 {
            dodge();
        }
    };
    // Arriving at the days screen (first time or back/forth) resets the chase.
    Effect::new(move |_| {
        if step.get() == Step::Days {
            dodges.set(0);
            shy_pos.set((0.0, 0.0));
            last_dodge.set(0.0);
        }
    });

    let toggle = |list: RwSignal<Vec<&'static str>>, id: &'static str| {
        list.update(|v| {
            if let Some(i) = v.iter().position(|x| *x == id) {
                v.remove(i);
            } else {
                v.push(id);
            }
        })
    };

    let names = |list: RwSignal<Vec<&'static str>>, src: &'static [Choice]| {
        move || {
            src.iter()
                .filter(|c| list.get().contains(&c.id))
                .map(|c| c.name)
                .collect::<Vec<_>>()
                .join(" · ")
        }
    };
    let join_names = names(joins, &JOINS);
    let vibe_names = names(vibes, &VIBES);

    let days_marked = move |a: Avail| {
        avail.with(|m| {
            m.iter()
                .filter(|&(_, v)| *v == a)
                .map(|(d, _)| *d)
                .collect::<Vec<_>>()
        })
    };
    let free_str = move || compress_days(&days_marked(Avail::Free));
    let maybe_str = move || compress_days(&days_marked(Avail::Maybe));
    let bday = move || avail.with(|m| m.get(&HER_BIRTHDAY).copied());

    let plan_text = move || {
        if not_free.get() {
            return "pedestrian × princedestrain kidney: september sync 🌵\nseptember's a no-go for me. rain check?\n—\ngenerated by the very serious scheduling instrument i built instead of just texting".to_string();
        }
        let mut lines = vec!["pedestrian × princedestrain kidney: september sync 🇲🇽".to_string()];
        let f = free_str();
        if !f.is_empty() {
            lines.push(format!("free: sept {f}"));
        }
        let mb = maybe_str();
        if !mb.is_empty() {
            lines.push(format!("maybe: sept {mb}"));
        }
        let j = join_names();
        if !j.is_empty() {
            lines.push(format!("tagging along: {j}"));
        }
        let v = vibe_names();
        if !v.is_empty() {
            lines.push(format!("vibes: {v}"));
        }
        if bday().is_some() {
            lines.push("🎂 and yes, the 26th is your birthday".to_string());
        }
        lines.push("—".to_string());
        lines.push(
            "generated by the very serious scheduling instrument i built instead of just texting"
                .to_string(),
        );
        lines.join("\n")
    };

    let copy_plan = move |_| {
        let clipboard = web_sys::window()
            .expect("no window? concerning")
            .navigator()
            .clipboard();
        let text = plan_text();
        // Fire and forget; the Promise resolves on its own time.
        let _ = clipboard.write_text(&text);
        copied_snapshot.set(Some(text));
    };

    // A little helper so each selectable card reads the same everywhere.
    let tile = move |c: &'static Choice, list: RwSignal<Vec<&'static str>>| {
        view! {
            <button
                class="tile"
                class:sel=move || list.get().contains(&c.id)
                on:click=move |_| toggle(list, c.id)
            >
                <span class="em">{c.emoji}</span>
                <span class="nm">{c.name}</span>
                <div class="nt">{c.note}</div>
            </button>
        }
    };

    // A little helper so "go back" reads the same everywhere.
    let back_button = move |target: Step| {
        view! {
            <button class="btn ghost back-btn" on:click=move |_| step.set(target)>"← back"</button>
        }
    };

    view! {
        <ThemeToggle />

        // progress markers — one per post-intro step
        <div class="progress" aria-hidden="true">
            <Show when=move || { step.get() > Step::Intro }>
                <span style="display:flex;align-items:center;gap:6px">
                    <span class="ht" class:on=move || { step.get() >= Step::Route }>"✈️"</span>
                </span>
                <span style="display:flex;align-items:center;gap:6px">
                    <span class="line" class:on=move || { step.get() >= Step::Days }></span>
                    <span class="ht" class:on=move || { step.get() >= Step::Days }>"🗓️"</span>
                </span>
                <span style="display:flex;align-items:center;gap:6px">
                    <span class="line" class:on=move || { step.get() >= Step::Join }></span>
                    <span class="ht" class:on=move || { step.get() >= Step::Join }>"🎒"</span>
                </span>
                <span style="display:flex;align-items:center;gap:6px">
                    <span class="line" class:on=move || { step.get() >= Step::Vibes }></span>
                    <span class="ht" class:on=move || { step.get() >= Step::Vibes }>"🌮"</span>
                </span>
                <span style="display:flex;align-items:center;gap:6px">
                    <span class="line" class:on=move || { step.get() >= Step::Done }></span>
                    <span class="ht" class:on=move || { step.get() >= Step::Done }>"💛"</span>
                </span>
            </Show>
        </div>

        // Confetti either way — saying no gets celebrated too.
        <Show when=move || step.get() == Step::Done>
            <Confetti />
        </Show>

        // ——— step 0 · hello ———
        <Show when=move || step.get() == Step::Intro>
            <div class="card">
                <span class="big-emoji" role="img" aria-label="airplane">"✈️"</span>
                <p class="eyebrow">"ola 🌊· pas grand-chose"</p>
                <h1>"i'm coming to your timezone 🇲🇽"</h1>
                <p class="sub">
                    "september 18 to 30. three cities, thirteen-ish days, and only one question (spanish version under construction 🚧): "
                    <em>"when are you free? tu es libre quand?"</em>
                </p>
                <div class="next-row">
                    <button class="btn" on:click=move |_| step.set(Step::Route)>"show me the plan →"</button>
                </div>
            </div>
        </Show>

        // ——— step 1 · the route (a briefing, not a menu) ———
        <Show when=move || step.get() == Step::Route>
            <div class="card">
                <p class="eyebrow">"le plan · el plan "</p>
                <h1>"where i'll be"</h1>
                <p class="sub">
                    "nothing to tap here. just mon rough travel plan of where i want to consume all of the tacos."
                </p>
                <div class="itin">
                    {LEGS.iter().map(|l| view! {
                        <div class="row" class:star=l.tag.is_some()>
                            <span class="pin">{l.emoji}</span>
                            <div class="mid">
                                <div class="nm">
                                    {l.name}
                                    {l.tag.map(|t| view! { <span class="tag">{t}</span> })}
                                </div>
                                <div class="nt">{l.note}</div>
                            </div>
                            <span class="dt">{l.dates}</span>
                        </div>
                    }).collect_view()}
                </div>
                <p class="sub fine">"🚨 attention: dates are able to move ±1 day"</p>
                <div class="next-row">
                    {back_button(Step::Intro)}
                    <button class="btn" on:click=move |_| step.set(Step::Days)>"okay, your turn →"</button>
                </div>
            </div>
        </Show>

        // ——— step 2 · her days ———
        <Show when=move || step.get() == Step::Days>
            <div class="card">
                <p class="eyebrow">"the actual point of all this"</p>
                <h1>"when are you free?"</h1>
                <p class="sub">
                    "tap una vez for " <strong>"free"</strong> ", deux fois for " <strong>"maybe"</strong>
                    ", three times to erase the evidence. ce n'est pas grave."
                </p>
                {LEGS.iter().filter(|l| !l.days.is_empty()).map(|l| view! {
                    <div class="day-group">
                        <div class="dg-name">
                            {l.emoji} " " {l.name}
                            {(l.days == BUSY_DAYS).then(|| view! { <span class="dg-busy">" · spoken for"</span> })}
                        </div>
                        <DayStrip days=l.days avail=avail />
                    </div>
                }).collect_view()}
                <div class="legend">
                    <span class="lg"><span class="sw free"></span>"free"</span>
                    <span class="lg"><span class="sw maybe"></span>"maybe"</span>
                </div>
                <Show when=move || bday().is_some()>
                    <p class="sub birthday-note">"🎂 sept 26 is your birthday. noted. filed. mais je ne te crois pas. my sources still say the 25th. possibly the 27th. one of those."</p>
                </Show>
                <div class="shy-row">
                    <button
                        class="btn shy-btn"
                        style:transform=move || {
                            let (x, y) = shy_pos.get();
                            format!("translate({x:.0}px, {y:.0}px)")
                        }
                        on:click=shy_click
                        on:pointermove=shy_hover
                    >
                        {move || if dodges.get() >= 3 { "…fine. i'll hold still" } else { "none of these days work 🙈" }}
                    </button>
                </div>
                <div class="next-row">
                    {back_button(Step::Route)}
                    <button
                        class="btn"
                        disabled=move || avail.with(|m| m.is_empty())
                        on:click=move |_| {
                            not_free.set(false);
                            step.set(Step::Join);
                        }
                    >
                        "next →"
                    </button>
                </div>
                <p class="shy">
                    {move || {
                        const LINES: [&str; 3] = [
                            "hm. that button seems shy. 🙈",
                            "it does cardio with me. bonne chance.",
                            "one more and it gives up. promis.",
                        ];
                        match dodges.get() {
                            0 => "",
                            n => LINES[((n - 1).min(2)) as usize],
                        }
                    }}
                </p>
            </div>
        </Show>

        // ——— step 3 · tag along? ———
        <Show when=move || step.get() == Step::Join>
            <div class="card">
                <p class="eyebrow">"optional · si tu veux"</p>
                <h1>"want to tag along anywhere?"</h1>
                <p class="sub">"multi-select, pas de stress. no pressure. this is the rsvp equivalent of a maybe."</p>
                <div class="tiles stack">
                    {JOINS.iter().map(|c| tile(c, joins)).collect_view()}
                </div>
                <div class="next-row">
                    {back_button(Step::Days)}
                    <button class="btn" on:click=move |_| step.set(Step::Vibes)>
                        {move || if joins.get().is_empty() { "skip this part (bold) →" } else { "next →" }}
                    </button>
                </div>
            </div>
        </Show>

        // ——— step 4 · vibes ———
        <Show when=move || step.get() == Step::Vibes>
            <div class="card">
                <p class="eyebrow">"last one, promise"</p>
                <h1>"and what should we do?"</h1>
                <p class="sub">"pick as many as you want. kidneys will be protected at all times."</p>
                <div class="tiles">
                    {VIBES.iter().map(|c| tile(c, vibes)).collect_view()}
                </div>
                <div class="next-row">
                    {back_button(Step::Join)}
                    <button class="btn" on:click=move |_| step.set(Step::Done)>"vámonos →"</button>
                </div>
            </div>
        </Show>

        // ——— step 5 · synced ———
        <Show when=move || step.get() == Step::Done>
            <div class="card">
                <div class="polaroid" aria-hidden="true">
                    {move || {
                        if not_free.get() { "🌵" }
                        else if bday().is_some() { "🎂" }
                        else { "🗓️" }
                    }}
                </div>
                <h1>
                    {move || {
                        if not_free.get() {
                            "sync failed. gracefully."
                        } else if bday().is_some() {
                            "synced. birthday detected 🎂"
                        } else {
                            "sync complete ✨"
                        }
                    }}
                </h1>
                <p class="sub">
                    {move || {
                        if not_free.get() {
                            "september's busy. it happens. the form accepts this with grace. la prochaine fois. 🌵"
                        } else {
                            "schrödinger's calendar: your days were both free and busy until you tapped. now le plan officially exists. j'adore physics."
                        }
                    }}
                </p>
                <Show when=move || !not_free.get()>
                <div class="summary">
                    <div class="row">
                        <span class="k">"free"</span>
                        <span class="v">
                            {move || {
                                let s = free_str();
                                if s.is_empty() { "—".to_string() } else { format!("sept {s}") }
                            }}
                        </span>
                    </div>
                    <Show when=move || !maybe_str().is_empty()>
                        <div class="row">
                            <span class="k">"maybe"</span>
                            <span class="v">{move || format!("sept {}", maybe_str())}</span>
                        </div>
                    </Show>
                    <div class="row">
                        <span class="k">"joining"</span>
                        <span class="v" style="font-size:16px">
                            {move || {
                                let s = join_names();
                                if s.is_empty() { "(negotiations open)".to_string() } else { s }
                            }}
                        </span>
                    </div>
                    <div class="row">
                        <span class="k">"vibes"</span>
                        <span class="v" style="font-size:16px">
                            {move || {
                                let s = vibe_names();
                                if s.is_empty() { "dealer's choice".to_string() } else { s }
                            }}
                        </span>
                    </div>
                </div>
                </Show>
                <div class="next-row">
                    <button
                        class="btn ghost back-btn"
                        on:click=move |_| {
                            step.set(if not_free.get_untracked() { Step::Days } else { Step::Vibes })
                        }
                    >
                        "← back"
                    </button>
                    <button class="btn" on:click=copy_plan>
                        {move || match copied_snapshot.get() {
                            Some(snap) if snap == plan_text() => "copied! 💛".to_string(),
                            Some(_) => "plan changed, sneaky.\n\n📋 copy again".to_string(),
                            None if not_free.get() => "📋 copy the rain check".to_string(),
                            None => "📋 copy & text it back".to_string(),
                        }}
                    </button>
                </div>
                <p class="ps">
                    <Show when=move || not_free.get()>
                        "p.s. no hard feelings. the button tried its best."
                    </Show>
                    <Show when=move || !not_free.get()>
                        "p.s. normal people share a google calendar."<br/>
                        "but i'm a weirdo, so i made a form instead. and it worked!"
                    </Show>
                    <br/>"made with love in my favorite programming language rust, a little wasm and a lot of google translate."
                </p>
            </div>
        </Show>
    }
}
